lib/url_shortener_web/router.ex
defmodule UrlShortenerWeb.Router do
  use UrlShortenerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  
  scope "/", UrlShortenerWeb do
    pipe_through :browser
    
    get "/", PageController, :index
    get "/:code", ShortenedUrlController, :show
  end
  
  # Other scopes may use custom stacks.
  scope "/api", UrlShortenerWeb do
    pipe_through :api

    post "/url", ShortenedUrlController, :create
  end
end

lib/url_shortener/application.ex
defmodule UrlShortener.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      UrlShortener.Repo,
      # Start the endpoint when the application starts
      UrlShortenerWeb.Endpoint
      # Starts a worker by calling: UrlShortener.Worker.start_link(arg)
      # {UrlShortener.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: UrlShortener.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    UrlShortenerWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/url_shortener/repo.ex
defmodule UrlShortener.Repo do
  use Ecto.Repo,
    otp_app: :url_shortener,
    adapter: Ecto.Adapters.Postgres
end

lib/url_shortener/shortened_urls.ex
defmodule UrlShortener.ShortenedUrl do
  use Ecto.Schema

  schema "shortened_urls" do
    field :code, :string
    field :url, :string
  end

  def changeset(shortened_url, params \\ %{}) do
    shortened_url
    |> Ecto.Changeset.cast(params, [:code, :url])
    |> Ecto.Changeset.validate_required([:code, :url])
  end
end

lib/url_shortener_web/controllers/page_controller.ex
defmodule UrlShortenerWeb.PageController do
  use UrlShortenerWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/url_shortener_web/controllers/shortened_url_controller.ex
defmodule UrlShortenerWeb.ShortenedUrlController do
  use UrlShortenerWeb, :controller

  def show(conn, %{"code" => code}) do
    shortened_url = UrlShortener.ShortenedUrl.get_url(code)
    
    redirect(conn, external: shortened_url.url)
  end

  def create(conn, %{"url" => url}) do
    code = Shortener.generate_code(6)
    case  UrlShortener.ShortenedUrl.create_url(code, url) do
      {:ok, url} ->
        json(conn, %{code: url.code})
      {:error, changeset} ->
        json(conn, %{error: "There was an error creating the shortened URL"})
    end
  end
end

lib/url_shortener_web/views/error_view.ex
defmodule UrlShortenerWeb.ErrorView do
  use UrlShortenerWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/url_shortener_web/views/layout_view.ex
defmodule UrlShortenerWeb.LayoutView do
  use UrlShortenerWeb, :view
end

lib/url_shortener_web/views/page_view.ex
defmodule UrlShortenerWeb.PageView do
  use UrlShortenerWeb, :view
end

lib/url_shortener_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "UrlShortener · Phoenix Framework" %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
      <section class="container">
        <a href="#" class="phx-logo">
          lynked.page
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/url_shortener_web/templates/page/index.html.eex
<div id="app">
</div>

lib/url_shortener_web/templates/shortened_url/new.html.eex
<h1>Create a Shortened URL</h1>

<%= form_for @changeset, Routes.shortened_url_path(@conn, :create), fn f -> %>
  <div>
    <%= text_input f, :name, placeholder: "URL" %>
  </div>
%>
<%= submit "Submit" %>
<% end %>